from fpdf import FPDF

# Create PDF document
pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()
pdf.set_font("Arial", size=12)

# Title
pdf.set_font("Arial", style='B', size=16)
pdf.cell(200, 10, "Super-Resolution Model for Image Enhancement", ln=True, align='C')
pdf.ln(10)

# Introduction
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "1. Introduction", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "This report presents a super-resolution model that enhances low-resolution images "
                       "using deep learning. The project is based on the SRCNN model, a convolutional neural network "
                       "designed to upscale images while preserving details. The goal is to generate high-quality images "
                       "from low-resolution inputs efficiently.")

# Literature Review
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "2. Literature Review", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "Super-resolution techniques have been widely studied in image processing. Traditional methods "
                       "like interpolation (bilinear, bicubic) often produce blurry results. Deep learning models, "
                       "especially convolutional neural networks (CNNs), have significantly improved image upscaling. "
                       "SRCNN, FSRCNN, and GAN-based models have demonstrated high performance in enhancing image quality.")

# Dataset & Preprocessing
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "3. Dataset and Preprocessing", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "The dataset used for training is the DIV2K dataset, which contains high-resolution images. "
                       "To create training pairs, we downscaled the images to generate low-resolution versions. "
                       "These pairs were then used to train the model to reconstruct high-resolution images from low-resolution inputs.")

# Model Architecture
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "4. Model Architecture", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "The model is based on the Super-Resolution Convolutional Neural Network (SRCNN). "
                       "It consists of three convolutional layers: "
                       "\n- The first layer extracts image features using a 9x9 kernel."
                       "\n- The second layer refines these features using a 1x1 kernel."
                       "\n- The final layer reconstructs the high-resolution image using a 5x5 kernel."
                       "\nThe model is trained using Mean Squared Error (MSE) loss and Adam optimizer.")

# Training and Results
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "5. Training and Results", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "The model was trained on the DIV2K dataset for 20 epochs with a batch size of 16. "
                       "The results were evaluated using Peak Signal-to-Noise Ratio (PSNR) and Structural Similarity Index (SSIM). "
                       "The model successfully improved image quality compared to traditional interpolation methods.")

# Visualizations
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "6. Visualizations", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "Below are sample results comparing low-resolution images, original high-resolution images, and "
                       "the super-resolution outputs generated by our model. The improvements in image sharpness and details "
                       "demonstrate the effectiveness of the approach.")

# Conclusion & Future Work
pdf.set_font("Arial", style='B', size=14)
pdf.cell(0, 10, "7. Conclusion and Future Work", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, "This project successfully implemented a super-resolution model that enhances low-resolution images. "
                       "The results show significant improvement in image quality. "
                       "Future work could involve using GAN-based models for even better enhancements and real-time applications.")

# Save the PDF
pdf.output("Super_Resolution_Report.pdf")

print("✅ Report generated successfully! Check 'Super_Resolution_Report.pdf' in your folder.")
